server:
  port: 8080
  context-path: "/rabbitmq"

spring:
  application:
    name: wind-rabbitmq
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
#    publisher-confirms: true
    virtual-host: /

